const interestData = [
  {
    title: "Accounting",
    items: [
      "Financial Accounting",
      "Cost Accounting",
      "Managerial Accounting",
      "Auditing",
      "Tax Accounting",
      "Forensic Accounting",
    ],
  },
  {
    title: "Finance",
    items: [
      "Investment Management",
      "Financial Risk Management",
      "Corporate Finance",
      "Public Finance",
      "Personal Finance",
    ],
  },
  {
    title: "Human Resources",
    items: [
      "Learning & Development",
      "Performance Management",
      "HR Information Systems",
      "Compensation & Benefits",
      "Recruiting & Staffing",
      "Organizational Structure",
      "Employee & Labor Relations",
      "Diversity Equity & Inclusion",
    ],
  },
  {
    title: "Information Technology",
    items: [
      "Systems Security",
      "Data Management",
      "IT Management",
      "Network Administration",
      "Software Development",
      "Web Development",
    ],
  },
  {
    title: "Legal",
    items: [
      "Litigation",
      "Risk Management",
      "Contract Law",
      "Import/Export Law",
      "Compliance Policies & Procedures",
      "Property Law",
      "Intellectual Property Law",
      "Employment Law",
      "Ethics",
      "Law Enforcement",
      "Criminal Justice",
    ],
  },
  {
    title: "Manufacturing",
    items: [
      "Plant Management",
      "Fabrication & Machining",
      "Reliability & Asset Management",
      "Procurement",
      "Distribution",
      "Production Installation",
    ],
  },
  {
    title: "Operations",
    items: [
      "Improve Processes",
      "LEAN & Six Sigma",
      "Production Planning & Control",
      "Quality Management",
      "Supply Chain Management",
      "Design Process",
    ],
  },
  {
    title: "Marketing & Communication",
    items: [
      "Sales Support",
      "Marketing Communications",
      "Advertising Strategy",
      "Pricing Strategy",
      "Market Research",
      "Social Media Strategy",
      "Brand Management",
      "Copy & Content Creation",
      "Imaging/Graphics",
    ],
  },
  {
    title: "Sales",
    items: [
      "Capture Management",
      "Building a Book of Business",
      "Channel Strategy",
      "Sales Forecasting",
      "Enterprise Sales",
      "Inside Sales",
      "Objection Handling",
      "Business Development",
    ],
  },
  {
    title: "Management",
    items: [
      "Delegation",
      "Emotional Intelligence",
      "Improve Processes",
      "Product Management",
      "Project Management",
      "Decision Making",
      "Negotiation Skills",
      "Develop Others",
      "Change Management",
      "Priority Management",
      "Effective Communication",
      "Conflict Management",
    ],
  },
  {
    title: "Leadership",
    items: [
      "Team Building",
      "Shaping Culture",
      "Setting Vision & Strategy",
      "Strategic Thinking",
      "Product Development",
      "Service Development",
      "Value Creation",
    ],
  },
  {
    title: "Healthcare",
    items: [
      "Dentistry",
      "Health Sciences",
      "Physician",
      "Veterinarian",
      "Pharmacist",
      "Healthcare Management",
      "Patient Care",
    ],
  },
  {
    title: "Education",
    items: [
      "Teaching",
      "Education Administration",
      "School Counseling",
      "Curriculum Development",
    ],
  },
  {
    title: "Consulting",
    items: [
      "Management Consulting",
      "Corporate Consulting",
      "Independent Consulting",
    ],
  },
  {
    title: "Government & Public Administration",
    items: [
      "Revenue & Taxation",
      "Law Enforcement",
      "Public Management & Administration",
      "Environmental & Resource Planning",
      "National Security",
      "Governance",
    ],
  },
  {
    title: "Customer Service",
    items: [
      "Customer Retention",
      "Customer Management",
      "Customer Support",
      "SaaS Customer Experience",
    ],
  },
  {
    title: "Engineering",
    items: [
      "Civil Engineering",
      "Chemical Engineering",
      "Mechanical Engineering",
      "Electrical Engineering",
      "Industrial Engineering",
      "Aerospace Engineering",
      "Biomedical Engineering",
      "Environmental Engineering",
      "Computer Engineering",
      "Materials/Textiles Engineering",
      "Nuclear Engineering",
      "Architecture",
    ],
  },
  {
    title: "Sciences",
    items: [
      "Agricultural Science",
      "Social Science",
      "Biology",
      "Chemistry",
      "Political Science",
      "Physics",
      "Psychology",
      "Mining & Petroleum",
    ],
  },
  {
    title: "Social Services",
    items: [
      "Therapists",
      "Probation Officer",
      "Rehabilitation Counselor",
      "Career Counselor",
      "Social Worker",
      "Substance Abuse Counselor",
      "Mental Health Counselor",
      "Clergy",
    ],
  },
  {
    title: "Creative / Design",
    items: [
      "Creative Arts",
      "Graphic Design",
      "Interior Design",
      "Product Design",
      "User Experience",
    ],
  },
];
